### ISSUE TITLE
Export-Handler für Wochenaufgaben-Antworten

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/Server#1]
_From @cbettinger on November 21, 2016 13:29_

Ich wünsche mir einen Handler, der eine CSV-Datei exportiert, in der für alle Wochenaufgaben im aktuellen Semester oder via URL-Parameter ID für eine bestimmte Wochenaufgabe alle Einsendungen (task_answer) enthalten sind.

Fremdschlüssel sollen über eine entsprechende View in der Datenbank aufgelöst werden.

Als Trennzeichen soll das Semikolon eingesetzt werden.

Der Zugriff auf den Handler soll über den gleichen Mechanismus wie beim Zugriff auf das Messenger-Formular abgesichert werden.

Bitte Anpassungen an der API in der Datei swagger.yaml dokumentieren.

_Copied from original issue: HundertTage/App#63_

**Comment by geht** [comment]
Der Export-Handler wurde in commit e0bb7651690a89fadcec5b90a5ac78c0e099341b umgesetzt.
Die SQL-Datei zum Erstellen der benötigten DB-Views befindet sich im commit e1b55ba27c74a75361a9e5ee204f50296c18bffc.
Die Swagger.yaml wurde in commit 193387dac55e5b7802d6d180ba185e2f3b36c5f4 angepasst.

Der Export-Handler ist unter dem Pfad `/export` erreichbar.
Ein Aufruf dieses Pfades liefert (sofern man sich korrekt authentifiziert hat) eine CSV-Datei aller beantworteter Wochenaufgaben des aktuellen Semesters.
Gibt man eine ID an (Beispiel: `/export?id=20`) so wird eine CSV-Datei mit den Antworten zu dieser bestimmten Wochenaufgabe geliefert.

Die Zeilen haben dabei folgenden Aufbau:
`"task_id";"title";"text";"user_id";"answer";"correct"`

Dabei gilt folgende Zuordnung;
`task_id` entspricht der ID der Wochenaufgabe
`title` entspricht dem Titel der Wochenaufgabe
`text` entspricht dem Text der entsprechenden Teilaufgabe der Wochenaufgabe
`user_id` entspricht der ID des Benutzers
`answer` entspricht der abgegeben Antwort des Benutzers zu der  entsprechenden Teilaufgabe
`correct` gibt an, ob die Antwort korrekt war oder nicht

**Comment by cbettinger** [comment]
Ich habe den neuen Handler noch etwas refaktorisiert. Könntest du bitte noch mal kurz testen?

**Comment by geht** [comment]
> Könntest du bitte noch mal kurz testen?

Funktioniert. Das Verhalten bei Angabe einer inkorrekten ID ist jetzt natürlich anders, der Browser versucht die Website zu laden und bekommt einen timeout, da vom Server keine Antwort mehr kommt.

**Comment by cbettinger** [comment]
Das ist Mist. Kannst du das kurz so anpassen, das in dem Fall eine leere Datei ausgespuckt wird? Vermutlich musst du die "return"-Statements rausnehmen und dann mal gucken, was passiert :)

**Comment by geht** [comment]
Ich hatte es vorher so, dass bei Angabe einer inkorrekten ID einfach die Daten geliefert werden, als hätte man gar keine ID angegeben.

Jetzt habe ich es so angepasst, dass bei Problemen mit der Anfrage eine leere Datei geliefert wird.

**Comment by cbettinger** [comment]
Sehr gut, danke!

**Comment by cbettinger** [comment]
Der Export aller Antworten funktioniert.

Der Export mit gültigem id-Parameter (http://100tage-dev.hochschule-trier.de:10080/export?id=20) funktionert bei mir nicht. Die Anfrage am Server dauert lange, dann Time-out.

Bei ungültiger id verhält sich der Server genauso.

Hast du vielleicht eine alte JAR-Datei auf den Test-Server kopiert?

**Comment by geht** [comment]
Diese Probleme habe ich auch schon festgestellt. Ich weiß nur leider noch nicht, woran es liegt.

Die JAR-Datei ist aktuell, ich habe sie gerade auch nochmal auf meinem lokalen Server getestet, da funktioniert alles.

Die Logfile auf dem Server hat mir bisher noch nicht weitergeholfen...
Da steht nur das `Handling EXPORT request...`, es wurde keinerlei Exception dort geloggt und ich weiß noch nicht genau, wo der Server nun steckenbleibt. Aber ich bleib dran.

**Comment by geht** [comment]
`parseUnsignedInt()` war der Übeltäter.
Die Methode gibt es erst seit Java 1.8 und der Server läuft auf Java 1.7

![](https://puu.sh/tTO4P/e6f32bf866.png)

Ich habe sie durch die `paseInt()` ausgetauscht, jetzt funktioniert es auch auf dem Testserver.

**Comment by cbettinger** [comment]
Supi, klappt. Kann ich schließen?

**Comment by geht** [comment]
Kann geschlossen werden. Sollen ich die neuen features (issue #1 und issue #3) auch schon in den develop mergen?

**Comment by cbettinger** [comment]
Kannst du.
