### ISSUE TITLE
Automatisches Versenden von Wochenaufgaben-Einladungen

### ISSUE THREAD

**Issue by cbettinger** [HundertTage/Server#3]
_From @cbettinger on November 21, 2016 12:56_

Der Server soll automatisch Event-Nachrichten an alle Nutzer senden, sobald das Start-Datum eines Events vom Typ Wochenaufgabe eintritt. Die Nachricht soll mit dem Event verknüpft sein und folgenden Text enthalten:

> Vielen Dank für die Teilnahme an der letzten Wochenaufgabe! Ab sofort kann die neue Wochenaufgabe "EVENT.TITLE" bearbeitet werden.

Ist die Wochenaufgabe die erste Wochenaufgabe im aktuellen Semester (event.semester == settings.current_semester), fällt der erste Satz weg.

_Copied from original issue: HundertTage/App#59_

**Comment by geht** [comment]
Die Funktionalität wurde in commit 5683ed75de5cfcb92f635596762973904dfd0231 umgesetzt.

Sobald der Server gestartet wird, wird ein Timer gestartet, der jede Stunde (Periode kann bei Bedarf geändert werden) überprüft, ob eine neue Einladung abgeschickt werden muss.

Damit abgecheckt werden kann, ob für eine Wochenaufgabe bereits eine Einladung verschickt wurde oder nicht, bedarf es einen neuen Tabelleneintrag "invitationSend" vom Typ Bit in der event-Tabelle der DB.

![](http://puu.sh/tznAl/27759cfc83.png)

Beispiel der ersten Wochenaufgabe im Semester:

![](https://puu.sh/tzoso/70fd868e98.png)

Beispiel der zweiten Wochenaufgabe:

![](https://puu.sh/tzot8/1202c1cb37.png)

Die Überschrift "Wochenaufgabe" kann bei Bedarf noch geändert werden.

**Comment by cbettinger** [comment]
Sehr schön! Stündliche Prüfungen finde ich ok.

Bitte noch ändern:
* Überschrift von "Wochenaufgabe" zu "Neue Wochenaufgabe"
* Neue Tabellenspalte von "invitationSend" zu "invitationSent"

**Comment by geht** [comment]
> Bitte noch ändern:
> 
> Überschrift von "Wochenaufgabe" zu "Neue Wochenaufgabe"
> Neue Tabellenspalte von "invitationSend" zu "invitationSent"

Wurde beides in commit 9a1fa03a35dfbd8ca8a09f87729b9725fe432411 angepasst.

**Comment by cbettinger** [comment]
Noch etwas: Die Klasse WOATimer scheint mir eine Klasse mit ausschließlich statischer Funktionalität zu sein. Um ein versehentliches Instanziieren der Klasse zu verhindern
* füge einen privaten Konstruktor ein
* mache die Klasse "final"

Füge bitte außerdem einen Punkt am Ende der Nachricht "WOATimer started with a period of %s ms" ein.

Und bitte packe alles von dem Top-Level-Paket "woa" in "hochschuletrier.hunderttage.server.woatimer".

**Comment by cbettinger** [comment]
TODO: Die SQL-Installationsskripte müssen angepasst werden. Das machen wir beim nächsten Meeting gemeinsam.

**Comment by geht** [comment]
> Noch etwas: Die Klasse WOATimer scheint mir eine Klasse mit ausschließlich statischer Funktionalität zu sein. Um ein versehentliches Instanziieren der Klasse zu verhindern
> 
> füge einen privaten Konstruktor ein
> mache die Klasse "final"
> Füge bitte außerdem einen Punkt am Ende der Nachricht "WOATimer started with a period of %s ms" ein.
> 
> Und bitte packe alles von dem Top-Level-Paket "woa" in "hochschuletrier.hunderttage.server.woatimer".

Whoops, das hatte ich übersehen. Wurde in 15be4dad595f97457df188ce19e7bcc2ec98fa46 korrigiert.

**Comment by cbettinger** [comment]
WOAs bei DB-Abfrage nach aufsteigendem Start-Datum sortieren.

**Comment by geht** [comment]
> WOAs bei DB-Abfrage nach aufsteigendem Start-Datum sortieren.

Select query wurde in commit 6c33baa9676ae4b519ad0da476d4db0dce12f855 angepasst.

**Comment by cbettinger** [comment]
Auf dem Produktiv-Server funktioniert das automatische Versenden von Einladungen nicht. Es werden keine Nachrichten versendet, das invitationSent-Flag bleibt bei false.

**Comment by geht** [comment]
Das Problem liegt beim Starten des WOATimers, siehe folgende Codezeilen: https://github.com/HundertTage/Server/blob/master/src/hochschuletrier/hunderttage/server/woatimer/WOATimer.java#L18-L25

Der Satz "Starting WOATimer..." taucht in den Logfiles noch auf.
Der Satz "WOATimer started with a period of %s ms." taucht nicht auf.

Der Timer wird aus einem noch unbekannten Grund erst gar nicht ausgeführt.
Da die Klasse Timer erst ab java version 1.5 verfügbar ist, auch hier nochmal die Frage: Auf welcher Java Version läuft denn der Produktivserver?

**Comment by cbettinger** [comment]
```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

**Comment by geht** [comment]
Ich habe jetzt mal von `Timer` umgestellt auf `ScheduledThreadPoolExecutor`, um den Task periodisch ausführen zu lassen (siehe commit 4b815e8b39a1468161e202b011478de92caa52ed) und auf meinem lokalen TestServer (erfolgreich) getestet.

**Comment by geht** [comment]
> Es könnte auch sein, dass die Zeile "WOATimer started..." nicht im Log auftaucht, weil diese Zeile ein anderes Log-Level als die Zeile "Starting WOATimer..." verwendet.

Das habe ich lokal getestet (hier taucht sie auf), die Zeile sollte trotz des unterschiedlichen Log-Levels auftauchen.

**Comment by cbettinger** [comment]
In Ordnung. Trotzdem stellt sich die Frage, warum hier unbedingt ein unterschiedliches Log-Level eingesetzt werden muss. Falls du keinen guten Grund siehst, vereinheitliche bitte an dieser Stelle das Log-Level. Verwende das Log-Level, welches auch sonst überall für positive Logs verwendet wurde.

**Comment by cbettinger** [comment]
Wenn du das für sinnvoll hältst, könntest du mir eine jar-Datei mit dem ScheduledThreadPoolExecutor erstellen und wir testen das kommenden Montag live auf dem Produktivserver :)

**Comment by geht** [comment]
> Falls du keinen guten Grund siehst, vereinheitliche bitte an dieser Stelle das Log-Level.

Das ist mir auch aufgefallen und wurde bereits mit commit 4b815e8b39a1468161e202b011478de92caa52ed auf `FINE` vereinheitlicht, man könnte allerdings stattdessen auch mit `INFO` loggen.

**Comment by geht** [comment]
Beim Testen auf dem Testserver ist mir aufgefallen, dass der Task zwar jetzt korrekt regelmäßig ausgeführt wird, allerdings das (Beginn- und End-)Datum der Wochenaufgaben nicht korrekt geparst wurde,

Hier wurden aufgrund des Patterns `yyyy-mm-dd hh:mm:ss` die Monate fälschlicherweise als Minuten interpretiert. Dies wurde mit commit 4f13dc11d4bb3f4798707b9fd2fa30e11074a3a9 behoben, durch Änderung des Patterns zu `yyyy-MM-dd hh:mm:ss`.

Auf dem TestServer habe ich in der Event-Tabelle noch das fehlende Bit eingepflegt, die Datenbank auf das neue Semester umgestellt und ein paar Test-Wochenaufgaben erstellt. Der automatische Versand funktioniert dort nun wie gewünscht.

Windows Phone Emulator (verbunden mit der Testdatenkbank)
![ss 2017-04-05 at 10 23 46](https://cloud.githubusercontent.com/assets/882090/24697097/3546036a-19ec-11e7-9f55-4b62804d0db9.png)

**Comment by cbettinger** [comment]
War ja klar :) Immer Ärger mit Lokalisierung. Bau mir eine JAR-Datei und wir testen das kommende Woche auf dem Produktiv-Server.

**Comment by cbettinger** [comment]
Scheint zu funktionieren. Bitte merge das in den develop und erstelle ein merge request für den master.
