### ISSUE TITLE
Klickbare Buttons in Push-Nachrichten

### ISSUE THREAD

**Issue by Seppo007** [HundertTage/Server#7]
Siehe Verweis auf App-Issue _https://github.com/HundertTage/App/issues/57_

Der Server muss dahingehend angepasst werden, dass eine neue Gruppe von Usern "Test Users" im Messenger zur Übermittlung von Push-Nachrichten ausgewählt werden können.
Nach Anpassungen im App-Projekt sind dies alle Geräte, die das Projekt im Debug-Mode builden.

Es muss bei Textnachrichtenübermittlung geprüft werden, ob eine URL im Message-Body enthalten ist.
Sollte dies der Fall sein, so soll im vom Server erstellten REST-Aufruf gesetzt werden, dass mit der Push-Nachricht ein Action-Button bereitgestellt wird. Die App kann dann beim Klick auf diesen Button in einem Callback den weiteren Vorgang bestimmen.
_(Label: "Link öffnen")_

Bei Event-Nachrichten soll ebenfalls ein entsprechender Action-Button bereitgestellt werden. Das Verhalten beim Klick auf diesen wird auch hier in einem Callback innerhalb der App vorgegeben.
_(Label: "Zum Event")_

**Comment by Seppo007** [comment]
Einführung einer neuen Gruppe "Test Users"
ba45cd478d41eeed9afdb64e87cc113944794cb8

**Comment by cbettinger** [comment]
Sowohl auf dem Test- als auch auf dem Development-Server ist eine neue Version online, in der das Segment "Test Users" als Empfänger ausgewählt werden kann.

**Comment by Seppo007** [comment]
iOS angepasst:
https://github.com/HundertTage/App/commit/b0e528b810c911f144d338608a4c15c04a1a0b82 (fehlerhafte Referenzierung, Klickbare Buttons sind im Server Branch unter # 7 abgelegt)

**Comment by Seppo007** [comment]
Windows Phone

**reine Message:**
![wp_plaintext](https://cloud.githubusercontent.com/assets/5859802/22430510/d21d62ca-e70e-11e6-816e-64d5566fc7d0.png)

**Message mit Url:**
![wp_url](https://cloud.githubusercontent.com/assets/5859802/22430524/dc9feeac-e70e-11e6-80e4-3896c10e5530.png)

**Event-Benachrichtigung:**
![wp_event](https://cloud.githubusercontent.com/assets/5859802/22430548/eea6d55c-e70e-11e6-8dae-37e0a0699e2a.png)

**Comment by Seppo007** [comment]
iOS

**reine Message + Aktion:**
![message1](https://cloud.githubusercontent.com/assets/5859802/22430694/56f7f1cc-e70f-11e6-9fc0-b0e28cbdbe5d.png)
![message2](https://cloud.githubusercontent.com/assets/5859802/22430709/5e5b805a-e70f-11e6-8cb0-20669b69cf38.png)

**Message mit Url + Aktion:**
![web1](https://cloud.githubusercontent.com/assets/5859802/22430726/6a3fcb60-e70f-11e6-9cbc-be8f1ac99130.png)
![web2](https://cloud.githubusercontent.com/assets/5859802/22430730/6d7bac7c-e70f-11e6-964f-76c288fa611c.png)

**Event-Benachrichtigung + Aktion:**
![event1](https://cloud.githubusercontent.com/assets/5859802/22430752/7a2a4f1e-e70f-11e6-90a8-6fd40197c9c3.png)
![event2](https://cloud.githubusercontent.com/assets/5859802/22430754/7b8bfede-e70f-11e6-94f4-dd8b67c217d6.png)

**Comment by cbettinger** [comment]
Wegen der iOS-Problematik sollen reine Textnachrichten verschickt werden können, die keine Action-Buttons erstellen. Somit sollen URLs (nicht klickbar) in Textnachrichten enthalten sein dürfen. Diese sollen von allen App-Varianten empfangen werden können.
